# Generated by Django 4.2.13 on 2024-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0004_remove_studentorclass_b_c_null_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentorclass',
            name='school_freelance_null_check',
        ),
        migrations.AddConstraint(
            model_name='studentorclass',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchased_class_hours__isnull', True), ('account_type', 'school'), ('school__isnull', False)), models.Q(('school__isnull', True), ('purchased_class_hours__isnull', False), ('account_type', 'freelance')), _connector='OR'), name='school_freelance_null_check'),
        ),
    ]
