# Generated by Django 4.2.13 on 2026-03-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentorclass',
            options={'ordering': ('teacher__surname', 'student_or_class_name'), 'verbose_name_plural': 'Students or Classes'},
        ),
    ]
