# Generated by Django 4.2.13 on 2026-05-09 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingClientSchoolStudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_student_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('student_level', models.CharField(choices=[('beginner', 'Beginner'), ('pre-intermediate', 'Pre-intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('purchased_group_class_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purchased_tutoring_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purchased_online_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_school', to='client_school.clientschool')),
            ],
            options={
                'verbose_name_plural': 'Client School Student Accounts',
                'ordering': ('client_student_name', 'client_student_name'),
                'unique_together': {('client_school', 'client_student_name')},
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
