# Generated by Django 4.2.13 on 2026-05-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0009_alter_studentorclass_options'),
        ('client_school_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingclientschoolstudentaccount',
            options={'ordering': ('client_school__school_name', 'client_student_name'), 'verbose_name_plural': 'Client School Student Accounts'},
        ),
        migrations.CreateModel(
            name='ClientSchoolClassEnrollmentHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_enrollment_type', models.CharField(choices=[('one_to_one_tutoring', 'One-to-one Tutoring'), ('two_to_one_tutoring', 'Two-to-one Tutoring'), ('online_tutoring', 'Online Tutoring'), ('group_class', 'Group Class')], default='one_to_one_tutoring', max_length=200)),
                ('client_group_accounts', models.ManyToManyField(blank=True, related_name='group_class_enrollments', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('client_school_one_to_one_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_tutoring_enrollment', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('client_school_online_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_enrollment', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('client_school_two_to_one_accounts', models.ManyToManyField(blank=True, related_name='two_to_one_tutoring_enrollments', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('student_or_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_student_or_class_record', to='student_account.studentorclass')),
            ],
            options={
                'verbose_name_plural': 'Client School Class Enrollment Handlers',
                'ordering': ('student_or_class__teacher__surname', 'class_enrollment_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='clientschoolclassenrollmenthandler',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('class_enrollment_type', 'one_to_one_tutoring'), ('client_school_one_to_one_account__isnull', False), ('client_school_online_account__isnull', True)), models.Q(('class_enrollment_type', 'two_to_one_tutoring'), ('client_school_one_to_one_account__isnull', True), ('client_school_online_account__isnull', True)), models.Q(('class_enrollment_type', 'online_tutoring'), ('client_school_online_account__isnull', False), ('client_school_one_to_one_account__isnull', True)), models.Q(('class_enrollment_type', 'group_class'), ('client_school_one_to_one_account__isnull', True), ('client_school_online_account__isnull', True)), _connector='OR'), name='enrollment_type_fk_consistency_check'),
        ),
    ]
