# Generated by Django 4.2.13 on 2026-05-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_accounting', '0002_alter_accountingclientschoolstudentaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientschoolclassenrollmenthandler',
            name='enrollment_type_fk_consistency_check',
        ),
        migrations.AddField(
            model_name='accountingclientschoolstudentaccount',
            name='company_hours_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingclientschoolstudentaccount',
            name='group_hours_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingclientschoolstudentaccount',
            name='online_hours_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingclientschoolstudentaccount',
            name='purchased_company_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='accountingclientschoolstudentaccount',
            name='tutoring_hours_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientschoolclassenrollmenthandler',
            name='client_school_company_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_enrollment', to='client_school_accounting.accountingclientschoolstudentaccount'),
        ),
        migrations.AlterField(
            model_name='clientschoolclassenrollmenthandler',
            name='class_enrollment_type',
            field=models.CharField(choices=[('one_to_one_tutoring', 'One-to-one Tutoring'), ('two_to_one_tutoring', 'Two-to-one Tutoring'), ('online_tutoring', 'Online Tutoring'), ('group_class', 'Group Class'), ('company_class', 'Company Class')], default='one_to_one_tutoring', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='accountingclientschoolstudentaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchased_group_class_hours__isnull', True), ('group_hours_expiration_date__isnull', True)), models.Q(('purchased_group_class_hours__isnull', False), ('group_hours_expiration_date__isnull', False)), _connector='OR'), name='group_hours_expiration_date_null_check'),
        ),
        migrations.AddConstraint(
            model_name='accountingclientschoolstudentaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchased_tutoring_hours__isnull', True), ('tutoring_hours_expiration_date__isnull', True)), models.Q(('purchased_tutoring_hours__isnull', False), ('tutoring_hours_expiration_date__isnull', False)), _connector='OR'), name='tutoring_hours_expiration_date_null_check'),
        ),
        migrations.AddConstraint(
            model_name='accountingclientschoolstudentaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchased_online_hours__isnull', True), ('online_hours_expiration_date__isnull', True)), models.Q(('purchased_online_hours__isnull', False), ('online_hours_expiration_date__isnull', False)), _connector='OR'), name='online_hours_expiration_date_null_check'),
        ),
        migrations.AddConstraint(
            model_name='accountingclientschoolstudentaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchased_company_hours__isnull', True), ('company_hours_expiration_date__isnull', True)), models.Q(('purchased_company_hours__isnull', False), ('company_hours_expiration_date__isnull', False)), _connector='OR'), name='company_hours_expiration_date_null_check'),
        ),
        migrations.AddConstraint(
            model_name='clientschoolclassenrollmenthandler',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('class_enrollment_type', 'one_to_one_tutoring'), ('client_school_one_to_one_account__isnull', False), ('client_school_online_account__isnull', True), ('client_school_company_account__isnull', True)), models.Q(('class_enrollment_type', 'two_to_one_tutoring'), ('client_school_one_to_one_account__isnull', True), ('client_school_online_account__isnull', True), ('client_school_company_account__isnull', True)), models.Q(('class_enrollment_type', 'online_tutoring'), ('client_school_online_account__isnull', False), ('client_school_one_to_one_account__isnull', True), ('client_school_company_account__isnull', True)), models.Q(('class_enrollment_type', 'group_class'), ('client_school_one_to_one_account__isnull', True), ('client_school_online_account__isnull', True), ('client_school_company_account__isnull', True)), models.Q(('class_enrollment_type', 'company_class'), ('client_school_company_account__isnull', False), ('client_school_one_to_one_account__isnull', True), ('client_school_online_account__isnull', True)), _connector='OR'), name='enrollment_type_fk_consistency_check'),
        ),
    ]
