# Generated by Django 4.2.13 on 2026-05-20 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0009_alter_studentorclass_options'),
        ('client_school_accounting', '0003_remove_clientschoolclassenrollmenthandler_enrollment_type_fk_consistency_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientschoolclassenrollmenthandler',
            name='student_or_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_student_or_class_record', to='student_account.studentorclass'),
        ),
    ]
