# Generated by Django 4.2.13 on 2026-05-22 02:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_school', '0001_initial'),
        ('client_school_accounting', '0004_alter_clientschoolclassenrollmenthandler_student_or_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientschoolclassenrollmenthandler',
            name='client_group_accounts',
        ),
        migrations.CreateModel(
            name='AccountingClientSchoolGroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_class_name', models.CharField(max_length=200)),
                ('student_level', models.CharField(choices=[('beginner', 'Beginner'), ('pre-intermediate', 'Pre-intermediate'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('client_group_class_accounts', models.ManyToManyField(blank=True, related_name='group_class_accounts', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('client_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_client_school', to='client_school.clientschool')),
            ],
            options={
                'verbose_name_plural': 'Client School Group Classes',
                'ordering': ('client_school__school_name', 'group_class_name'),
                'unique_together': {('client_school', 'group_class_name')},
            },
        ),
        migrations.AddField(
            model_name='clientschoolclassenrollmenthandler',
            name='client_group_class',
            field=models.ManyToManyField(blank=True, related_name='group_class_account_enrollment', to='client_school_accounting.accountingclientschoolgroupclass'),
        ),
    ]
