# Generated by Django 4.2.13 on 2026-05-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_accounting', '0005_remove_clientschoolclassenrollmenthandler_client_group_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientschoolclassenrollmenthandler',
            name='client_group_class',
        ),
        migrations.AddField(
            model_name='clientschoolclassenrollmenthandler',
            name='client_group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_class_account_enrollment', to='client_school_accounting.accountingclientschoolgroupclass'),
        ),
    ]
