# Generated by Django 4.2.13 on 2024-07-19 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('school', '0002_school_scheduling_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='scheduling_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_teacher', to='user_profiles.userprofile'),
        ),
    ]
