# Generated by Django 4.2.13 on 2024-09-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_scheduling_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['scheduling_teacher', 'school_name']},
        ),
    ]
