# Generated by Django 4.2.13 on 2025-06-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('school', '0004_alter_school_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('scheduling_teacher', 'school_name')},
        ),
    ]
