# Generated by Django 4.2.13 on 2026-05-09 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0003_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('other_information', models.TextField(blank=True, default='')),
                ('school_owner', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'client_school_owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
    ]
