# Generated by Django 4.2.13 on 2026-05-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_scheduling', '0004_scheduledclass_location'),
        ('client_school_accounting', '0006_remove_clientschoolclassenrollmenthandler_client_group_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClassMeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('class_date', models.DateField()),
                ('class_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_meeting_records', to='client_school_accounting.accountingclientschoolgroupclass')),
                ('scheduled_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_class_meeting_record', to='class_scheduling.scheduledclass')),
            ],
            options={
                'verbose_name_plural': 'Group Class Meeting Records',
                'ordering': ('-class_date', 'group_class__group_class_name'),
            },
        ),
        migrations.CreateModel(
            name='GroupClassStudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('same_day_cancellation', 'Same_Day_Cancellation')], default='scheduled', max_length=300)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('group_class_meeting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_records', to='client_school_group_attendance.groupclassmeetingrecord')),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_attendance_records', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Group Class Student Attendance Records',
                'ordering': ('-group_class_meeting_record__class_date', 'student_account__client_student_name'),
                'unique_together': {('group_class_meeting_record', 'student_account')},
            },
        ),
    ]
