# Generated by Django 4.2.13 on 2025-03-15 08:22

import accounting.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField()),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.utils.validate_number_of_hours_purchased])),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_or_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_or_class_tuition_transactions', to='student_account.studentorclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tuition_transactions', to='user_profiles.userprofile')),
            ],
        ),
    ]
