# Generated by Django 4.2.13 on 2025-03-28 03:10

import accounting.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
        ('class_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(editable=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_or_class', models.ForeignKey(limit_choices_to={'account_type': 'freelance'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_or_class_tuition_transactions', to='student_account.studentorclass')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedHoursModificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(choices=[('tuition_payment_add', 'Tuition Payment'), ('tuition_refund_deduct', 'Tuition Refund'), ('class_status_modification_add', 'Class Status Modification: Hours Added'), ('class_status_modification_deduct', 'Class Status Modification: Hours Deducted')], default='class_status_modification_deduct', max_length=200)),
                ('previous_purchased_class_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_purchased_class_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('modified_scheduled_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_status_purchased_hours_modification', to='class_scheduling.scheduledclass')),
                ('student_or_class', models.ForeignKey(limit_choices_to={'account_type': 'freelance'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_or_class_purchased_hours_modification', to='student_account.studentorclass')),
                ('tuition_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_purchased_hours_modification', to='accounting.freelancetuitiontransactionrecord')),
            ],
            options={
                'ordering': ('student_or_class__teacher', 'time_stamp', 'student_or_class__student_or_class_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='purchasedhoursmodificationrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tuition_transaction__isnull', True), models.Q(('modification_type', 'class_status_modification_add'), ('modification_type', 'class_status_modification_deduct'), _connector='OR'), ('modified_scheduled_class__isnull', False)), models.Q(('modified_scheduled_class__isnull', True), models.Q(('modification_type', 'tuition_payment_add'), ('modification_type', 'tuition_refund_deduct'), _connector='OR'), ('tuition_transaction__isnull', False)), _connector='OR'), name='tuition_transaction_modified_scheduled_class_null_check'),
        ),
    ]
