# Generated by Django 4.2.13 on 2025-03-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_freelancetuitiontransactionrecord_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancetuitiontransactionrecord',
            name='teacher',
        ),
    ]
