# Generated by Django 4.2.13 on 2025-03-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
        ('accounting', '0003_remove_freelancetuitiontransactionrecord_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancetuitiontransactionrecord',
            name='student_or_class',
            field=models.ForeignKey(limit_choices_to={'account_type': 'freelance'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_or_class_tuition_transactions', to='student_account.studentorclass'),
        ),
    ]
