# Generated by Django 4.2.13 on 2025-02-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_start_time', models.TimeField(blank=True, null=True)),
                ('recurring_finish_time', models.TimeField(blank=True, null=True)),
                ('recurring_day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('student_or_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_student_or_class', to='student_account.studentorclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_teacher', to='user_profiles.userprofile')),
            ],
        ),
    ]
