# Generated by Django 4.2.13 on 2025-05-16 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("recurring_scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="recurringscheduledclass",
            managers=[
                ("custom_query", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RecurringClassAppliedMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduling_month",
                    models.SmallIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                (
                    "scheduling_year",
                    models.SmallIntegerField(
                        default=2025,
                        validators=[
                            django.core.validators.MinValueValidator(2025),
                            django.core.validators.MaxValueValidator(2035),
                        ],
                    ),
                ),
                (
                    "recurring_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recurring_scheduling.recurringscheduledclass",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-scheduling_year",
                    "-scheduling_month",
                    "recurring_class__teacher__user__username",
                    "recurring_class__student_or_class__student_or_class_name",
                ],
                "unique_together": {
                    ("scheduling_month", "scheduling_year", "recurring_class")
                },
            },
        ),
    ]
