# Generated by Django 4.2.13 on 2026-03-09 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_scheduling', '0002_alter_recurringscheduledclass_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringclassappliedmonthly',
            options={'ordering': ['-scheduling_year', '-scheduling_month', 'recurring_class__teacher__user__username', 'recurring_class__student_or_class__student_or_class_name'], 'verbose_name_plural': 'Recurring Classes Applied Monthly'},
        ),
        migrations.AlterModelOptions(
            name='recurringscheduledclass',
            options={'verbose_name_plural': 'Recurring Scheduled Classes'},
        ),
        migrations.AlterField(
            model_name='recurringclassappliedmonthly',
            name='scheduling_year',
            field=models.SmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2035)]),
        ),
    ]
