# Generated by Django 4.2.13 on 2026-03-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0002_userprofile_account_type"),
        (
            "recurring_scheduling",
            "0003_alter_recurringclassappliedmonthly_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringscheduledclass",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"account_type": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_teacher",
                to="user_profiles.userprofile",
            ),
        ),
    ]
