# Generated by Django 4.2.13 on 2026-03-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
        ("recurring_scheduling", "0004_alter_recurringscheduledclass_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringscheduledclass",
            name="recurring_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_class_location",
                to="venues.venuespace",
            ),
        ),
    ]
