# Generated by Django 4.2.13 on 2024-09-30 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_account', '0008_remove_studentorclass_school_freelance_null_check_and_more'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('class_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancellation_request', 'Cancellation_Request'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('same_day_cancellation', 'Same_Day_Cancellation')], default='scheduled', max_length=300)),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('class_content', models.TextField(blank=True, default='')),
                ('student_or_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_student_or_class', to='student_account.studentorclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_teacher', to='user_profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Scheduled Classes',
                'ordering': ['-date', 'teacher', 'start_time'],
            },
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
