# Generated by Django 4.2.13 on 2026-03-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledclass',
            name='class_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('same_day_cancellation', 'Same_Day_Cancellation')], default='scheduled', max_length=300),
        ),
    ]
