# Generated by Django 4.2.13 on 2026-03-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_account_type'),
        ('class_scheduling', '0002_alter_scheduledclass_class_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledclass',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_teacher', to='user_profiles.userprofile'),
        ),
    ]
