# Generated by Django 4.2.13 on 2026-03-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('class_scheduling', '0003_alter_scheduledclass_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_class_location', to='venues.venuespace'),
        ),
    ]
