# Generated by Django 4.2.13 on 2026-03-16 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0002_userprofile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('other_information', models.TextField(blank=True, default='')),
                ('venue_owner', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'venue_owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
            ],
            options={
                'ordering': ['venue_name'],
            },
        ),
        migrations.CreateModel(
            name='VenueSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('number_of_seats', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'ordering': ['venue__venue_name', 'space_name'],
                'unique_together': {('venue', 'space_name')},
            },
        ),
    ]
