# Generated by Django 4.2.13 on 2026-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('venue_owner', 'Venue_Owner')], default='teacher', max_length=200),
        ),
    ]
