# Generated by Django 4.2.13 on 2026-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('client_school_owner', 'Client_School_Owner'), ('teacher', 'Teacher'), ('venue_owner', 'Venue_Owner')], default='teacher', max_length=200),
        ),
    ]
