# Generated by Django 4.2.13 on 2026-05-27 07:28

import accounting.validation
import client_school_transactions.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_school_accounting', '0006_remove_clientschoolclassenrollmenthandler_client_group_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSCompanyClassTuitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_class_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Company Classes Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='CSGroupClassTuitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('12_weeks', '12 Weeks'), ('30_weeks', '30 Weeks'), ('60_weeks', '60 Weeks')], default='12_weeks', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Group Classes Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='CSOnlineTuitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months'), ('24_months', '24 Months')], default='6_months', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Online Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='CSTutoringTuitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months'), ('24_months', '24 Months')], default='6_months', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Tutoring Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='CST2To1TutoringTuitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=16500, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months'), ('24_months', '24 Months')], default='6_months', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('primary_student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_to_one_tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('shared_student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_to_one_shared_tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Two-to-one Tutoring Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='CSPurchasedHoursModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('one_to_one_tutoring', 'One-to-one Tutoring'), ('two_to_one_tutoring', 'Two-to-one Tutoring'), ('online_tutoring', 'Online Tutoring'), ('group_class', 'Group Class'), ('company_class', 'Company Class')], max_length=200)),
                ('modification_type', models.CharField(choices=[('tuition_payment_add', 'Tuition Payment'), ('tuition_refund_deduct', 'Tuition Refund'), ('class_status_modification_add', 'Class Status Modification: Hours Added'), ('class_status_modification_deduct', 'Class Status Modification: Hours Deducted')], default='class_status_modification_deduct', max_length=200)),
                ('previous_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modifications', to='client_school_accounting.clientschoolclassenrollmenthandler')),
                ('company_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.cscompanyclasstuitionrecord')),
                ('group_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.csgroupclasstuitionrecord')),
                ('online_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.csonlinetuitionrecord')),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modifications', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('tutoring_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.cstutoringtuitionrecord')),
                ('two_to_one_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.cst2to1tutoringtuitionrecord')),
            ],
            options={
                'verbose_name_plural': 'Client School Purchased Hours Modification Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='cspurchasedhoursmodification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('class_type', 'one_to_one_tutoring'), ('tutoring_transaction__isnull', False), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'two_to_one_tutoring'), ('two_to_one_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'online_tutoring'), ('online_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'group_class'), ('group_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'company_class'), ('company_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True)), models.Q(('modification_type', 'class_status_modification_add'), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True), ('bridge__isnull', False)), models.Q(('modification_type', 'class_status_modification_deduct'), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True), ('bridge__isnull', False)), _connector='OR'), name='client_school_modification_type_consistency_check'),
        ),
    ]
