# Generated by Django 4.2.13 on 2026-05-15 04:24

import accounting.validation
import client_school_transactions.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_school_accounting', '0003_remove_clientschoolclassenrollmenthandler_enrollment_type_fk_consistency_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSchoolTutoringTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months'), ('24_months', '24 Months')], default='6_months', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(limit_choices_to={'purchased_tutoring_hours__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Tutoring Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
    ]
