# Generated by Django 4.2.13 on 2026-06-06 10:00

import client_school_transactions.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscompanyclasstuitionrecord',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount]),
        ),
        migrations.AlterField(
            model_name='csgroupclasstuitionrecord',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount]),
        ),
        migrations.AlterField(
            model_name='csonlinetuitionrecord',
            name='transaction_amount',
            field=models.PositiveIntegerField(validators=[client_school_transactions.validation.validate_tuition_transaction_amount]),
        ),
        migrations.AlterField(
            model_name='cst2to1tutoringtuitionrecord',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=16500, validators=[client_school_transactions.validation.validate_tuition_transaction_amount]),
        ),
        migrations.AlterField(
            model_name='cstutoringtuitionrecord',
            name='transaction_amount',
            field=models.PositiveIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount]),
        ),
    ]
