# Generated by Django 4.2.13 on 2026-05-16 07:10

import accounting.validation
import client_school_transactions.validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_accounting', '0003_remove_clientschoolclassenrollmenthandler_enrollment_type_fk_consistency_check_and_more'),
        ('client_school_transactions', '0002_clientschool2to1tutoringtuitiontransactionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientschool2to1tutoringtuitiontransactionrecord',
            name='primary_student_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_to_one_tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount'),
        ),
        migrations.AlterField(
            model_name='clientschool2to1tutoringtuitiontransactionrecord',
            name='shared_student_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_to_one_shared_tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount'),
        ),
        migrations.AlterField(
            model_name='clientschooltutoringtuitiontransactionrecord',
            name='student_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount'),
        ),
        migrations.CreateModel(
            name='ClientSchoolOnlineTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('6_months', '6 Months'), ('12_months', '12 Months'), ('24_months', '24 Months')], default='6_months', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Online Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='ClientSchoolGroupClassesTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(choices=[('12_weeks', '12 Weeks'), ('30_weeks', '30 Weeks'), ('60_weeks', '60 Weeks')], default='12_weeks', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Group Classes Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='ClientSchoolCompanyClassesTuitionTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.PositiveSmallIntegerField(default=33000, validators=[client_school_transactions.validation.validate_tuition_transaction_amount])),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=200)),
                ('class_hours_purchased_or_refunded', models.PositiveSmallIntegerField(validators=[accounting.validation.validate_number_of_hours_purchased])),
                ('expiration_period', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(700)])),
                ('administrator_name', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_class_tuition_transactions', to='client_school_accounting.accountingclientschoolstudentaccount')),
            ],
            options={
                'verbose_name_plural': 'Company Classes Tuition Transaction Records',
                'ordering': ('-time_stamp',),
            },
        ),
    ]
