# Generated by Django 4.2.13 on 2026-05-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_accounting', '0003_remove_clientschoolclassenrollmenthandler_enrollment_type_fk_consistency_check_and_more'),
        ('client_school_transactions', '0003_alter_clientschool2to1tutoringtuitiontransactionrecord_primary_student_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSchoolPurchasedHoursModificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('one_to_one_tutoring', 'One-to-one Tutoring'), ('two_to_one_tutoring', 'Two-to-one Tutoring'), ('online_tutoring', 'Online Tutoring'), ('group_class', 'Group Class'), ('company_class', 'Company Class')], max_length=200)),
                ('modification_type', models.CharField(choices=[('tuition_payment_add', 'Tuition Payment'), ('tuition_refund_deduct', 'Tuition Refund'), ('class_status_modification_add', 'Class Status Modification: Hours Added'), ('class_status_modification_deduct', 'Class Status Modification: Hours Deducted')], default='class_status_modification_deduct', max_length=200)),
                ('previous_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modifications', to='client_school_accounting.clientschoolclassenrollmenthandler')),
                ('company_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.clientschoolcompanyclassestuitiontransactionrecord')),
                ('group_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.clientschoolgroupclassestuitiontransactionrecord')),
                ('online_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.clientschoolonlinetuitiontransactionrecord')),
                ('student_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modifications', to='client_school_accounting.accountingclientschoolstudentaccount')),
                ('tutoring_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.clientschooltutoringtuitiontransactionrecord')),
                ('two_to_one_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_hours_modification', to='client_school_transactions.clientschool2to1tutoringtuitiontransactionrecord')),
            ],
            options={
                'verbose_name_plural': 'Client School Purchased Hours Modification Records',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='clientschoolpurchasedhoursmodificationrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('class_type', 'one_to_one_tutoring'), ('tutoring_transaction__isnull', False), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'two_to_one_tutoring'), ('two_to_one_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'online_tutoring'), ('online_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'group_class'), ('group_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('company_transaction__isnull', True)), models.Q(('class_type', 'company_class'), ('company_transaction__isnull', False), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True)), models.Q(('modification_type', 'class_status_modification_add'), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True), ('bridge__isnull', False)), models.Q(('modification_type', 'class_status_modification_deduct'), ('tutoring_transaction__isnull', True), ('two_to_one_transaction__isnull', True), ('online_transaction__isnull', True), ('group_transaction__isnull', True), ('company_transaction__isnull', True), ('bridge__isnull', False)), _connector='OR'), name='client_school_modification_type_consistency_check'),
        ),
    ]
