# Generated by Django 4.2.13 on 2026-05-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_school_transactions', '0004_clientschoolpurchasedhoursmodificationrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientschool2to1tutoringtuitiontransactionrecord',
            options={'ordering': ('-time_stamp',), 'verbose_name_plural': 'Two-to-one Tutoring Tuition Transaction Records'},
        ),
    ]
